name = "external-auth-rule-eval"
workers_dev = true
compatibility_date = "2024-08-06"
main = "index.js"

[[kv_namespaces]]
binding = "KV"
id = "<update>"

[vars]
TEAM_DOMAIN="<update>.cloudflareaccess.com"
DEBUG=false