name = "external-auth-rule-eval"
account_id = "<fill in>"
workers_dev = true
compatibility_date = "2022-06-10"
main = "index.js"

kv_namespaces = [
    # namespace: 
  { binding = "KV", id = "<fill in>", preview_id = "<fill in>" },
]

[vars]
TEAM_DOMAIN="<update>.cloudflareaccess.com"
DEBUG=false